#!/usr/bin/env bash
# Deploy the whole app to AWS: the Lambda, the buckets, and the web page on CloudFront.
#
#   scripts/deploy.sh
#
# Needs: AWS CLI and SAM CLI installed, and AWS credentials that can create
# CloudFormation, S3, Lambda, IAM and CloudFront resources (aws configure / SSO).
# The first deploy takes several minutes because CloudFront is slow to create.
#
# Optional environment variables:
#   STACK_NAME    CloudFormation stack name (default: quickdrop)
#   AWS_REGION    region to deploy to (default: your AWS CLI default region)
#   LOCAL_ORIGIN  extra origin allowed to call the backend, for running the page
#                 on your laptop (default: http://localhost:8000)
set -euo pipefail

cd "$(dirname "$0")/.."

STACK_NAME="${STACK_NAME:-quickdrop}"
REGION="${AWS_REGION:-$(aws configure get region || true)}"
LOCAL_ORIGIN="${LOCAL_ORIGIN:-http://localhost:8000}"

for tool in aws sam; do
  command -v "$tool" >/dev/null || { echo "Missing '$tool'. Install it first." >&2; exit 1; }
done
[ -n "$REGION" ] || { echo "No region set. Run 'aws configure' or set AWS_REGION." >&2; exit 1; }

# A first deploy that fails rolls back and leaves the stack in ROLLBACK_COMPLETE, which
# CloudFormation cannot update. It has nothing worth keeping, so delete it and start clean.
stack_status() {
  aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
    --query "Stacks[0].StackStatus" --output text 2>/dev/null || true
}
STATUS="$(stack_status)"
if [ "$STATUS" = "ROLLBACK_IN_PROGRESS" ]; then
  echo "Waiting for an earlier failed attempt to finish rolling back (don't press Ctrl+C)..."
  aws cloudformation wait stack-rollback-complete --stack-name "$STACK_NAME" --region "$REGION" || true
  STATUS="$(stack_status)"
fi
if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
  echo "Removing the failed earlier attempt of '$STACK_NAME'..."
  aws cloudformation delete-stack --stack-name "$STACK_NAME" --region "$REGION"
  aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME" --region "$REGION"
fi

echo "1/3 Deploying stack '$STACK_NAME' to $REGION..."
sam build --template-file infra/template.yaml
sam deploy \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --resolve-s3 \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides "LocalOrigin=$LOCAL_ORIGIN" \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset

output() {
  aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}
SITE_URL="$(output SiteUrl)"
FUNCTION_URL="$(output FunctionUrl)"
SITE_BUCKET="$(output SiteBucketName)"

echo "2/3 Uploading the web page..."
# config.js is excluded here and generated below, so frontend/config.js in the repo
# (the one you edit by hand for the console version) is never touched.
aws s3 sync frontend/ "s3://$SITE_BUCKET" --region "$REGION" --delete \
  --exclude "config.js" --exclude "README.md"

CONFIG_FILE="$(mktemp)"
trap 'rm -f "$CONFIG_FILE"' EXIT
cat > "$CONFIG_FILE" <<EOF
// Generated by scripts/deploy.sh for this deployment.
window.APP_CONFIG = {
  FUNCTION_URL: "$FUNCTION_URL",
};
EOF
aws s3 cp "$CONFIG_FILE" "s3://$SITE_BUCKET/config.js" --region "$REGION" \
  --content-type "application/javascript" --cache-control "no-store"

echo "3/3 Done."
echo
echo "  Open the app: $SITE_URL"
echo "  Backend URL:  $FUNCTION_URL"
echo
echo "Check the backend end to end:"
echo "  python3 scripts/smoke_test.py $FUNCTION_URL"
